# Generated by Django 2.0.2 on 2018-02-22 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_name', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=250)),
                ('placeholder', models.CharField(default='', max_length=500)),
                ('type', models.CharField(choices=[('textarea', 'Textarea'), ('text', 'Text'), ('email', 'Email'), ('password', 'Password'), ('richtext', 'Richtext Box'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Dropdown select')], max_length=20)),
                ('meta_options', models.TextField(default='{}')),
                ('order', models.IntegerField(unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PromotionField')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Promotion')),
            ],
        ),
    ]
