# Generated by Django 2.0.2 on 2018-03-13 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('action', 'Action'), ('trigger', 'Trigger')], max_length=255)),
                ('interaction_type', models.SmallIntegerField(choices=[(1, 'Simple Question'), (2, 'Simple Message'), (3, 'Send a Message'), (4, 'Send a Card'), (5, 'Send Multiple Cards'), (6, 'Send Attachment'), (7, 'Webhook & HTTP Request'), (8, 'Scheduler'), (9, 'Send Promotional')])),
                ('data', models.TextField(default='{}')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='messengerbot.Flow')),
            ],
        ),
        migrations.CreateModel(
            name='MessengerBotProfile',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('page_uuid', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('long_lived_access_token', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_switched_on', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='bot',
            field=models.ManyToManyField(related_name='bot', to='messengerbot.MessengerBotProfile'),
        ),
    ]
