# Generated by Django 2.0.2 on 2018-04-03 13:20

import backend.apps.messengerbot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messengerbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowconversation',
            old_name='data',
            new_name='content',
        ),
        migrations.AddField(
            model_name='promotion',
            name='caption',
            field=models.TextField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='promotion',
            name='content',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=backend.apps.messengerbot.models.upload_promotion_thumbnail),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messengerbotprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
